
import { Metadata } from "../../node_modules/next/types";


export const metadata: Metadata = {
  title: "Weather Monitoring App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
